apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: SQL_DB
  name: postgres
spec:
  containers:
    - image: postgres:15 
      name: postgres
      resources: {}
      env:
      - name: POSTGRES_PORT
        value: "5432"
      envFrom:
      - configMapRef:
          name: postgress-username
      - secretRef:
          name: postgress-passkey
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}