apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: initcontainer
  name: initcontainer
spec:
  initContainers:
  - image: busybox
    name: initcontainer-1
    command:
    - sleep
    args:
    - "5"
  - image: busybox
    name: initcontainer-2
    command:
    - sleep
    args:
    - "5"
    resources: {}
  containers:
  - image: nginx
    name: proxy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}