# kubectl create secret generic --from-literal=POSTGRES_PASSWORD=kubernetes postgress-passkey --dry-run=client -o yaml > secrets.yaml

apiVersion: v1
data:
  POSTGRES_PASSWORD: a3ViZXJuZXRlcw==
kind: Secret
metadata:
  creationTimestamp: null
  name: postgress-passkey
  
  
# To encode a value - echo -n "kubernetes" | base64
# To decode a value - echo -n "a3ViZXJuZXRlcw==" | base64 --decode
